version: 0.1

phases:
  #install:
    #commands:
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - npm run build
  #post_build:
    #commands:

artifacts:
  files:
    - public/**/*
  #discard-paths: yes
  #base-directory: location
